const constants = {
    FILLINPUT: 'FILL_INPUT',
    CLICKELEMENT: 'CLICK_ELEMENT',
    SIGNINBUTTON: 'SIGN_IN_BUTTON',
    SIGNUPBUTTON: 'SIGN_UP_BUTTON',
    SUBMITBUTTON: 'SUBMIT_BUTTON',
    EMAILINPUT: 'EMAIL_INPUT',
    PASSWORDINPUT: 'PASSWORD_INPUT',
    FIRSTNAMEINPUT: 'FIRST_NAME_INPUT',
    LASTNAMEINPUT: 'LAST_NAME_INPUT',
    MOBILENUMBERINPUT: 'MOBILE_NUMBER_INPUT',
    SIGNINSECTION: 'SIGN_IN_SECTION',
    SIGNUPSECTION: 'SIGN_UP_SECTION',
    ADDRESSSECTION: 'ADDRESS_SECTION',
    ADDRESSINPUT: 'ADDRESS_INPUT',
    CREDITCARDSECTION: 'CREDIT_CARD_SECTION',
    CREDITDEBITCARDNUMBERINPUT: "CREDIT_DEBIT_CARD_NUMBER_INPUT",
    CVVNUMBERINPUT: "CVV_NUMBER_INPUT",
    EXPIRATIONDATEINPUT: "EXPIRATION_DATE_INPUT",
    POSTALCODEINPUT: "POSTAL_CODE_INPUT",
    MENUSECTION: "MENU_SECTION",
    PAYMENTMENUSECTION: "PAYMENT_MENU_SECTION",
    PYAMENTMETHODADDSECTION: "PYAMENT_METHOD_ADD_SECTION",
    SAVEADDRESSSECTION: "SAVE_ADDRESS_SECTION",
    CHOOSESTORESECTION: "CHOOSE_STORE_SECTION"
}

module.exports = constants;